### ISSUE TITLE
Entropy

### ISSUE THREAD

**Issue by pqwy** [yomimono/ocaml-certify#1]
Hey,

Just a heads-up: directly mixing into the RNG via `Rng.reseed` is deprecated on `master`, which will get released **Any Day Now™** as `0.5`. The new, officially sanctioned way to kick-start randomness on Unix and without Lwt will be [this](https://github.com/mirleft/ocaml-nocrypto/blob/master/unix/nocrypto_entropy_unix.mli) API from `nocrypto.unix`.

Reporting, to help make `ocaml-certify` a model app for the relevant APIs.

**Comment by yomimono** [comment]
Rad, thanks. :)

**Comment by yomimono** [comment]
New commits take this into account.  Thanks for the simpler API; it's quite a bit more convenient.

**Comment by pqwy** [comment]
It's even simpler if you don't care about the theoretical case of someone trying to invoke `--help` or `--version` on a Unix system that has neither `/dev/urandom` nor `/dev/random`.

You could just move the call to `initialize` from entry-points in `Csr` and `Selfsign` to module-level in `Common`, and forget that entropy was ever a thing. E.g. somewhere near the top of `common.ml`:

```
let () = Nocrypto_entropy_unix.initialize ()
```

But it's perfectly cromulent as it is.
