### ISSUE TITLE
`csr` should write to `csr.pem` by default

### ISSUE THREAD

**Issue by reynir** [yomimono/ocaml-certify#12]
`csr` should write to `csr.pem` by default to be consistent with the default csr argument of `sign`.

**Comment by yomimono** [comment]
Fair point.  I changed this in [44abc2abc96712ab3c6b380e4e807aef2e6c4d94](https://github.com/yomimono/ocaml-certify/commit/44abc2abc96712ab3c6b380e4e807aef2e6c4d94).  Do you need a release?

**Comment by reynir** [comment]
Excellent, thanks! I swear I was going to do it myself eventually :-) It's ok, I don't need a release.
