### ISSUE TITLE
CI failures in test due to openssl output changes

### ISSUE THREAD

**Issue by hannesm** [yomimono/ocaml-certify#18]
over at https://ci.ocaml.org/ocaml/opam-repository/pr/14581 I encountered some test failures with certify 0.2.0 (see https://ci.ocaml.org/log/saved/docker-build-0f9a2d41b40580c541a6f5b3d90db344/5a9e51a2b8bb38db76197a65a3a993541135f1ee as an example). The reason being `Key length RSA4096 was not the requested 4096`.

In the test script the following command is used to figure out the actual key length:
```
actual_length=$(${OPENSSL} x509 -in ${CERTDIR}/ca_out.pem -text -noout | grep Public-Key|sed 's/Public-Key: (//;s/ bit)//;s/ //
g')
[ "$actual_length" != "${KEY_LENGTH}" ] && {
```

and it looks like openssl's output changed at some point (now it is `RSA Public-Key: (4096 bit)`). I'm not entirely sure how to "fix" the testsuite though - to work with old and new openssl I guess the easiest is to compare a bit fuzzy (allowing `RSA`):
```
[ "$actual_length" != "${KEY_LENGTH}" && "$actual_length" != "RSA${KEY_LENGTH}" ] && {
```

but there are likely better solutions around (modify the `sed` command etc.).

**Comment by yomimono** [comment]
Fixed in https://github.com/yomimono/ocaml-certify/commit/c6e7a95659291c3f918bd0591d5d3ae1df1fff8c .  Thanks for the report!
